name: Init New Repo with Generator

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Name of the new GitHub repo"
        required: true

jobs:
  create-repo:
    runs-on: self-hosted  # using your own runner where yo is already installed
    steps:
      - name: Create GitHub repository with API
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/user/repos \
            -d '{"name":"${{ github.event.inputs.repo_name }}","private":false}'

      - name: Clone the newly created repo
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository_owner }}/${{ github.event.inputs.repo_name }}.git

      - name: Run Yeoman in repo
        run: |
          cd ${{ github.event.inputs.repo_name }}
          # run your custom generator here
          yo ondc-node

      - name: Push generated files to Repo
        run: |
          cd ${{ github.event.inputs.repo_name }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add files generated by Yeoman"
          git push origin main
