name: Create Node Repo

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Name of the new GitHub repo"
        required: true

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create GitHub repository
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const repoName = context.payload.inputs.repo_name;
            const response = await github.rest.repos.createInOrg({
              org: context.repo.owner,
              name: repoName,
              private: false
            });
            core.setOutput("clone_url", response.data.clone_url);

      - name: Setup Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Clone new repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/${{ github.event.inputs.repo_name }}.git
          cd ${{ github.event.inputs.repo_name }}

      - name: Initialize Node project
        run: |
          cd ${{ github.event.inputs.repo_name }}
          npm init -y

          # Overwrite package.json
          echo '{
            "name": "${{ github.event.inputs.repo_name }}",
            "version": "1.0.0",
            "main": "index.js",
            "scripts": {
              "start": "node index.js"
            }
          }' > package.json

          # Create index.js
          echo 'console.log("Hello from ${{ github.event.inputs.repo_name }}!");' > index.js

          # Create .gitignore
          echo "node_modules/" > .gitignore

          # Create README
          echo "# ${{ github.event.inputs.repo_name }}" > README.md

      - name: Commit and push
        run: |
          cd ${{ github.event.inputs.repo_name }}
          git add .
          git commit -m "Initial commit - Node.js boilerplate"
          git branch -M main
          git push origin main
