name: Init New Repo with Generator

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Name of the new GitHub repo"
        required: true

jobs:
  create-repo:
    runs-on: self-hosted  # since you're using your own runner
    steps:
      - name: Create GitHub repository with API
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/user/repos \
            -d '{"name":"${{ github.event.inputs.repo_name }}","private":false}'

      - name: Clone the new repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/${{ github.event.inputs.repo_name }}.git
          cd ${{ github.event.inputs.repo_name }}

      - name: Scaffold New Project with Yeoman
        run: |
          cd ${{ github.event.inputs.repo_name }}
          yo ondc-node --skip-install --no-insight --defaults

      - name: Commit and push generated files
        run: |
          cd ${{ github.event.inputs.repo_name }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "⚠️ No files generated by Yeoman. Skipping commit."
          else
            git commit -m "Initial commit from Yeoman generator"
            git push origin main
          fi
